name: CI

on:
  push:
  pull_request:
    types: [assigned, opened, synchronize, reopened, edited, ready_for_review]

jobs:
  pep_and_audit:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fetch tags
      run: git fetch --prune --unshallow --tags
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Lint with flake8
      run: |
        python -m pip install --upgrade pip flake8
        flake8 --count
    # Make sure that packaging will work
    - name: pep517 build
      run: |
        python -m pip install --upgrade setuptools pep517 twine
        python -m pep517.build --source .
        twine check dist/*
    - name: Security audit
      run: |
        python -m pip install --upgrade bandit
        bandit -r . -c .bandit.yaml

  initial_tests:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fetch tags
      run: git fetch --prune --unshallow --tags
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install and build
      run: |
        sudo apt-get install libxml2-utils
        python -m pip install --upgrade pip setuptools
        python -m pip install -e .[test]
    - name: Test without optional deps
      run: pytest --open-files

  dev_deps_tests:
    runs-on: ubuntu-latest
    needs: [pep_and_audit, initial_tests]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fetch tags
      run: git fetch --prune --unshallow --tags
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install and build
      run: |
        sudo apt-get install libxml2-utils
        python -m pip install --upgrade pip setuptools
        python -m pip install git+https://github.com/astropy/astropy.git@master#egg=astropy
        python -m pip install -e .[test]
    - name: Test with dev deps
      run: pytest --open-files
